---
- name: Ensure dependencies are installed.
  become: true
  ansible.builtin.apt:
    name: "{{ install_packages }}"
    state: present
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Set ansible_distribution for Kali and Debian
  ansible.builtin.set_fact:
    # https://fostips.com/install-latest-firefox-non-esr-debian/#rb-Method-3-Install-Firefox-from-Ubuntu-2004-Repository
    ansible_distribution_release: "focal"
  when: (ansible_distribution_release == "kali-rolling") or (ansible_distribution | lower == "debian")

- name: Add Mozilla Firefox PPA repository {{ ansible_distribution_release }}
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
    codename: "{{ ansible_distribution_release }}"

- name: Create apt preferences file for Mozilla Firefox
  become: true
  ansible.builtin.copy:
    content: |
      Package: *
      Pin: release o=LP-PPA-mozillateam
      Pin-Priority: 1001
    dest: /etc/apt/preferences.d/mozilla-firefox
    mode: 0644

- name: Create apt configuration file for unattended upgrades of Mozilla Firefox
  become: true
  ansible.builtin.copy:
    content: 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:{{ ansible_distribution_release }}";'
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
    mode: 0644

- name: Install Mozilla Firefox
  become: true
  ansible.builtin.apt:
    name: firefox
    update_cache: yes
