---
- name: Include OS-Specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yaml"

- name: Include OS-Specific tasks
  ansible.builtin.include_tasks: "{{ ansible_os_family }}.yaml"
